### ISSUE TITLE
Command to show all supported dictionaries.

### ISSUE THREAD

**Issue by willbasky** [willbasky/TibetCli#25]
- [x] show all dictionary`s name with command `tibet show names`. Done [#39](https://github.com/willbasky/TibetCli/pull/39)
- [x] show all dictionary`s descriptions with command `tibet show meta`. Done [#39](https://github.com/willbasky/TibetCli/pull/39)
- [x] show information on a particular dic with command `tibet show -d <id or name of dic>`. Need #38 

The [data about all dictionaries](https://github.com/christiansteinert/tibetan-dictionary/blob/master/webapp/settings/dictlist.js).

**Comment by princerachit** [comment]
I am working on this.

**Comment by willbasky** [comment]
@princerachit How do you do?
